### ISSUE TITLE
Complicated Config

### ISSUE THREAD

**Issue by Cheezik** [rogeraabbccdd/Rekordbox-NowPlaying#1]
Hey, i dont understand what token you mean by "Discord token". is it supposted to be My discord token Or Discord application Token or What?

**Comment by rogeraabbccdd** [comment]
Hi, sorry for late reply.
"Discord token" means Discord Application ID for Disocrd Rich Presence.
This project is discontinued, please consider using [Now Playing](https://www.nowplaying2.com/) or other software.
